### ISSUE TITLE
能提供一下Textbox.md中提到的voc_label_text_xml_for_ssd.py吗？

### ISSUE THREAD

**Issue by MaFuyan** [tongpi/basicOCR#20]
感谢～

**Comment by yushanshan05** [comment]
I could give you the file of voc_label_text_xml_for_ssd.py . This file just convet SynthText/gt.mat to labels of txt. But SSD require the labels of xml.   Next, I  also need convert the txt to xml。  
So I think it is not enough to have the  file of voc_label_text_xml_for_ssd.py. Are you sure you only need this?

**Comment by MaFuyan** [comment]
Thanks for your reply. Actually, I have converted gt.mat to example.txt or example.xml by Matlab. But I also want to get voc_label_text_xml_for_ssd.py to know how python do that. Thanks.

**Comment by yushanshan05** [comment]
OK, please give me your email!

**Comment by yushanshan05** [comment]
# -*- coding: utf-8 -*-
#将.mat按照h5py的格式读进去，将voc_xml格式需要的信息保存到labels_for_xml，保存格式为txt

import pickle
import os
from os import listdir, getcwd
from os.path import join
import cv2
import scipy.io as sio
import numpy as np
import math

def convert(size, box):
    dw = 1./size[0]
    dh = 1./size[1]
    x = (box[0] + box[1])/2.0
    y = (box[2] + box[3])/2.0
    w = box[1] - box[0]
    h = box[3] - box[2]
    x = x*dw
    w = w*dw
    y = y*dh
    h = h*dh
    return (x,y,w,h)


wd = getcwd()
in_db = sio.loadmat('/opt/datasets/data/str/SynthText/gt.mat') 
count = 0
imageNum = len(in_db['imnames'][0])
print imageNum

#list_file = open('train_text_total_1.txt', 'w')

for index in np.arange(imageNum):
    ss = str(in_db['imnames'][0][index])    

    strqq = "/opt/datasets/data/str/SynthText/" + ss[3:len(ss)-2]
    
    img = cv2.imread(strqq)

    if img!=None:    
        imgNameIndex1=strqq.rfind('/')
        imgNameIndex2=strqq.rfind('.jpg')
        imgName = strqq[imgNameIndex1+1:imgNameIndex2]
        #print imgName
        #print strqq
        
        w = img.shape[1]
        h = img.shape[0]
        out_label = open('./textdata/labels_for_xml/%s.txt'%(imgName), 'w')
        wordBB = in_db['wordBB'][0][index]
        if len(wordBB.shape) == 3:  
            wordBBNum = wordBB.shape[-1]
            validflag = False
            for i2 in xrange(wordBB.shape[-1]):                                 
                bb = wordBB[:,:,i2]                            
                bb = np.c_[bb, bb[:,0]]                            
                
                (tl, tr, br, bl) = bb[0:, 0:4].T  
                
                h1 = math.sqrt(math.pow((bl[0]-tl[0]),2) + math.pow((bl[1]-tl[1]),2))
                h2 = math.sqrt(math.pow((br[0]-tr[0]),2) + math.pow((br[1]-tr[1]),2))
                h_p = (h1+h2)/2   
                w1 = math.sqrt(math.pow((tr[0]-tl[0]),2) + math.pow((tr[1]-tl[1]),2))
                w2 = math.sqrt(math.pow((bl[0]-br[0]),2) + math.pow((bl[1]-br[1]),2))
                w_p = (w1+w2)/2
                
                if (h_p < 0.1)or(w_p < 0.1):
                    continue                 
               
                #b依次为最小的X，最大的X，最小的Y,最大的Y
                x_min = min(tl[0],tr[0],bl[0],br[0])
                x_max = max(tl[0],tr[0],bl[0],br[0])
                y_min = min(tl[1],tr[1],bl[1],br[1])
                y_max = max(tl[1],tr[1],bl[1],br[1]) 
                x_min = max(0, x_min)
                y_min = max(0, y_min)
                x_max = min(w-1, x_max)
                y_max = min(h-1, y_max)
                
                b = (w,h,x_min, x_max, y_min, y_max)
                
                validflag=True
                out_label.write(str(0) + " " + " ".join([str(a) for a in b]) + '\n') 
            
            if (validflag == False):
                continue;
        else:
            wordBBNum = 1
            bb = wordBB                            
            bb = np.c_[bb, bb[:,0]]                            
            
            (tl, tr, br, bl) = bb[0:, 0:4].T

            h1 = math.sqrt(math.pow((bl[0]-tl[0]),2) + math.pow((bl[1]-tl[1]),2))
            h2 = math.sqrt(math.pow((br[0]-tr[0]),2) + math.pow((br[1]-tr[1]),2))
            h_p = (h1+h2)/2   
            w1 = math.sqrt(math.pow((tr[0]-tl[0]),2) + math.pow((tr[1]-tl[1]),2))
            w2 = math.sqrt(math.pow((bl[0]-br[0]),2) + math.pow((bl[1]-br[1]),2))
            w_p = (w1+w2)/2
            
            if (h_p < 0.1)or(w_p < 0.1):
                continue             

            #b依次为最小的X，最大的X，最小的Y,最大的Y
            x_min = min(tl[0],tr[0],bl[0],br[0])
            x_max = max(tl[0],tr[0],bl[0],br[0])
            y_min = min(tl[1],tr[1],bl[1],br[1])
            y_max = max(tl[1],tr[1],bl[1],br[1])
            x_min = max(0, x_min)
            y_min = max(0, y_min)
            x_max = min(w-1, x_max)
            y_max = min(h-1, y_max)
            b = (w,h,x_min, x_max, y_min, y_max) 
            
            out_label.write(str(0) + " " + " ".join([str(a) for a in b]) + '\n') 
        
        #cv2.imwrite('./textdata/images_1/%s.jpg'%(imgName), img)
        #list_file.write('%s/textdata/images/%s.jpg\n'%(wd,imgName))        
        out_label.close()
        count +=1
    print(count)

**Comment by MaFuyan** [comment]
@yushanshan05      
mafuyanscuec@gmail.com    
Thanks.
