### ISSUE TITLE
多GPU训练loss不对，单GPU训练没有问题

### ISSUE THREAD

**Issue by SDASDASA** [tongpi/basicOCR#21]
麻烦问一下，crnn, 我用多个gpu训练的loss感觉不对，与单gpu训练相同Loss值的模型，预测结果非常差，单gpu训练的模型预测是正确的。@ wulivicte，请问您遇到过这种问题吗，怎么解决的，非常感谢。

**Comment by YoungMiao** [comment]
@SDASDASA 你好，在crnn训练上我一直采用单个gpu训练，所以没有遇到过你说的问题

**Comment by SDASDASA** [comment]
@wulivicte 好的，谢谢你
