### ISSUE TITLE
关于环境配置的疑问

### ISSUE THREAD

**Issue by Vivianwxf** [tongpi/basicOCR#22]
您好，我看textbox实验的内容，环境配置的问题，请教如何配置呢？Ubuntu14.04系统下配安装docker？“服务器上用nvidia-docker从镜像gds/keras-th-tf-opencv中新建了caffe_ys容器。按照caffe的依赖文件，并编译GPU版本。”这句话不理解╮(╯▽╰)╭

**Comment by YoungMiao** [comment]
@Vivianwxf “gds/keras-th-tf-opencv”的镜像是我们本地的docker镜像，建议你可以在ubuntu上安装gpu版的tensorflow为基础，之后进行caffe gpu的编译，docker只是我们的一个基于容器的管理方式
