### ISSUE TITLE
请问中文语料库的解压密码是什么, crnn 模型

### ISSUE THREAD

**Issue by ethan-funny** [tongpi/basicOCR#26]
@YoungMiao ，我从另外一个 issue 看到你提供了百度云的中文语料库的下载地址：http://pan.baidu.com/s/1jHYJeh4 密码：fdtk。

我下载下来后，发现需要解压密码，请问解压密码是什么？谢谢！

**Comment by YoungMiao** [comment]
@ethan-funny 抱歉，链接: https://pan.baidu.com/s/1GwkgMooV3iWrsqyAlNchbg 密码: 1b7y，下载这个即可，是相同的
